export interface PeriodTiming {
  startTime: string;
  endTime: string;
}

export interface Faculty {
  id: string;
  name: string;
  subjects: string[];
  maxPeriodsPerDay?: number;
  isAbsent?: boolean;
  assignedBatches?: string[]; // batch IDs this faculty is exclusively locked to; empty/undefined = unrestricted
}

export const WEEKDAYS = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'] as const;
export type DayOfWeek = typeof WEEKDAYS[number];

export interface Batch {
  id: string;
  building: string;
  yearCategory: string;
  name: string;
  roomNumber: string;
  periods: PeriodTiming[];
  subjects: {
    subject: string;
    count: number;
  }[];
}

export type TimetableStatus = 'Draft' | 'Finalized' | 'Archived';

export interface Allocation {
  batchId: string;
  periodIndex: number;
  facultyId: string;
  subject: string;
  autoGenerated?: boolean;
  manualEdited?: boolean;
  frozen?: boolean;
  explanation?: string[];
  vacatedFacultyId?: string;   // set when the original faculty went absent after generation
  vacatedFacultyName?: string; // cached name, so the UI can show it even if faculty is later deleted
}

export interface Timetable {
  id: string;
  date: string; // YYYY-MM-DD
  status: TimetableStatus;
  allocations: Allocation[];
}

export interface SchedulerSettings {
  pcmbWeight: number;
  languageWeight: number;
  maxDailyPeriods: number;
  weekStartDay: 'Monday' | 'Sunday';
  enableGapOptimization: boolean;
  enableConsecutivePeriodAvoidance: boolean;
}

export interface AuditLog {
  id: string;
  timestamp: number;
  action: 'MANUAL_OVERRIDE' | 'FREEZE_TOGGLE' | 'STATUS_CHANGE';
  batchId?: string;
  periodIndex?: number;
  previousFacultyId?: string;
  newFacultyId?: string;
  reason?: string;
}