export interface PeriodTiming {
  startTime: string;
  endTime: string;
}

export interface Faculty {
  id: string;
  name: string;
  subjects: string[];
  maxPeriodsPerDay?: number;
}

export interface Batch {
  id: string;
  building: string;
  yearCategory: string;
  name: string;
  roomNumber: string;
  periods: PeriodTiming[];
  subjects: {
    subject: string;
    count: number;
  }[];
}

// --- V2 ENGINE ENHANCEMENTS ---

export type TimetableStatus = 'Draft' | 'Finalized' | 'Archived';

export interface Allocation {
  batchId: string;
  periodIndex: number;
  facultyId: string;
  subject: string;
  // Cell State Metadata
  autoGenerated?: boolean;
  manualEdited?: boolean;
  frozen?: boolean;
  // Scheduler Transparency
  explanation?: string[];
}

export interface Timetable {
  id: string;
  date: string; // YYYY-MM-DD
  status: TimetableStatus;
  allocations: Allocation[];
}

export interface SchedulerSettings {
  pcmbWeight: number;
  languageWeight: number;
  maxDailyPeriods: number;
  weekStartDay: 'Monday' | 'Sunday';
  enableGapOptimization: boolean;
  enableConsecutivePeriodAvoidance: boolean;
  enableMissedSubjectRecovery: boolean;
  enableFacultyRotation: boolean;
}

export interface AuditLog {
  id: string;
  timestamp: number;
  action: 'MANUAL_OVERRIDE' | 'FREEZE_TOGGLE' | 'STATUS_CHANGE';
  batchId?: string;
  periodIndex?: number;
  previousFacultyId?: string;
  newFacultyId?: string;
  reason?: string;
}
export interface Faculty {
  id: string;
  name: string;
  subjects: string[];
  maxPeriodsPerDay?: number;
  isAbsent?: boolean; // NEW: Absence tracking
}