import type { Faculty } from '../types';

export const HARDCODED_FACULTIES: Faculty[] = [
  // --- BIOLOGY (29) ---
  { id: "fac_bio_1", name: "DEEPA", subjects: ["Biology"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_bio_2", name: "JOSMY", subjects: ["Biology"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_bio_3", name: "VIDHYA GAYATHRI", subjects: ["Biology"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_bio_4", name: "LAXMI PATIL", subjects: ["Biology"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_bio_5", name: "APEKSHA H S", subjects: ["Biology"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_bio_6", name: "PRATHIKSHA K", subjects: ["Biology"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_bio_7", name: "VISHNAVI K C", subjects: ["Biology"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_bio_8", name: "KAUSHIK S N", subjects: ["Biology"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_bio_9", name: "ABSATH", subjects: ["Biology"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_bio_10", name: "SMITHA", subjects: ["Biology"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_bio_11", name: "RAMYA", subjects: ["Biology"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_bio_12", name: "APEKSHA NAIK", subjects: ["Biology"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_bio_13", name: "SURAKSHITHA K", subjects: ["Biology"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_bio_14", name: "JEVITA PREMA", subjects: ["Biology"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_bio_15", name: "P PRAJVITH RAI", subjects: ["Biology"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_bio_16", name: "PAVITHRA D BAPAT", subjects: ["Biology"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_bio_17", name: "YASHWANTH", subjects: ["Biology"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_bio_18", name: "JANANI B V", subjects: ["Biology"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_bio_19", name: "VINDHYA M J", subjects: ["Biology"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_bio_20", name: "GANGADHARA V", subjects: ["Biology"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_bio_21", name: "DR ROOPA P", subjects: ["Biology"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_bio_22", name: "APEKSHA HEGDE", subjects: ["Biology"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_bio_23", name: "DEEKSHITH", subjects: ["Biology"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_bio_24", name: "VAISHNAVI", subjects: ["Biology"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_bio_25", name: "BIJU M K", subjects: ["Biology"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_bio_26", name: "SUNIL STEPHEN", subjects: ["Biology"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_bio_27", name: "PRIYANKA K J", subjects: ["Biology"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_bio_28", name: "SAI SHRUTHI B", subjects: ["Biology"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_bio_29", name: "SMITHA SHANKAR", subjects: ["Biology"], maxPeriodsPerDay: 4, isAbsent: false },

  // --- CHEMISTRY (32) ---
  { id: "fac_chem_1", name: "DEVRAJ V", subjects: ["Chemistry"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_chem_2", name: "RAINA HENCIL", subjects: ["Chemistry"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_chem_3", name: "JAIS ANTONY", subjects: ["Chemistry"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_chem_4", name: "DR.NAGESWARA", subjects: ["Chemistry"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_chem_5", name: "HARISHA", subjects: ["Chemistry"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_chem_6", name: "PREETHIKA DSOUZA", subjects: ["Chemistry"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_chem_7", name: "SHRIKANTH", subjects: ["Chemistry"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_chem_8", name: "SURESH BABU", subjects: ["Chemistry"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_chem_9", name: "SHIVRAJ K", subjects: ["Chemistry"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_chem_10", name: "RAM GANESH", subjects: ["Chemistry"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_chem_11", name: "JINO K JOHN", subjects: ["Chemistry"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_chem_12", name: "SHREESHA V G", subjects: ["Chemistry"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_chem_13", name: "PRIYA K", subjects: ["Chemistry"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_chem_14", name: "RAGHU BABU SAJJA", subjects: ["Chemistry"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_chem_15", name: "SUKESH SHETTY", subjects: ["Chemistry"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_chem_16", name: "SUJIT KUMAR GIRI", subjects: ["Chemistry"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_chem_17", name: "THEJASHREE", subjects: ["Chemistry"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_chem_18", name: "KAVANA H V", subjects: ["Chemistry"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_chem_19", name: "K SHIVA PRASAD", subjects: ["Chemistry"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_chem_20", name: "DEVIPRASAD", subjects: ["Chemistry"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_chem_21", name: "SEEMASHREE B M", subjects: ["Chemistry"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_chem_22", name: "ASHWINI", subjects: ["Chemistry"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_chem_23", name: "DEEKSHITHA", subjects: ["Chemistry"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_chem_24", name: "RAMYASHREE R", subjects: ["Chemistry"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_chem_25", name: "SYAM PRASAD", subjects: ["Chemistry"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_chem_26", name: "SANMITHA KUMARI", subjects: ["Chemistry"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_chem_27", name: "BHIMANA GOWDA", subjects: ["Chemistry"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_chem_28", name: "SOWJANYA SALIAN", subjects: ["Chemistry"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_chem_29", name: "DEVENDRA K", subjects: ["Chemistry"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_chem_30", name: "PRASAD S", subjects: ["Chemistry"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_chem_31", name: "SHREYA P", subjects: ["Chemistry"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_chem_32", name: "SHWETHNA KUNDER", subjects: ["Chemistry"], maxPeriodsPerDay: 4, isAbsent: false },

  // --- ENGLISH (12) ---
  { id: "fac_eng_1", name: "KESHAVATHI ENG", subjects: ["English"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_eng_2", name: "ANJANI", subjects: ["English"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_eng_3", name: "PRABAVATHI", subjects: ["English"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_eng_4", name: "RASMITHA SUVARNA", subjects: ["English"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_eng_5", name: "VIDHYA", subjects: ["English"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_eng_6", name: "JEEVAN PRADEEP", subjects: ["English"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_eng_7", name: "RASHMI MAHESH", subjects: ["English"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_eng_8", name: "MILANA T M", subjects: ["English"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_eng_9", name: "BHAGYALAKSHMI", subjects: ["English"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_eng_10", name: "FOUZIYA D B", subjects: ["English"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_eng_11", name: "VIDHYA NAVEEN", subjects: ["English"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_eng_12", name: "PRAJNA K", subjects: ["English"], maxPeriodsPerDay: 4, isAbsent: false },

  // --- MATHEMATICS (22) ---
  { id: "fac_math_1", name: "PRASADI M", subjects: ["Mathematics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_math_2", name: "GRISHIN JAMES", subjects: ["Mathematics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_math_3", name: "VARUN U", subjects: ["Mathematics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_math_4", name: "NISCHITHA", subjects: ["Mathematics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_math_5", name: "NITHA K JOY", subjects: ["Mathematics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_math_6", name: "VAISHNAVI", subjects: ["Mathematics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_math_7", name: "RAVIKANTH", subjects: ["Mathematics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_math_8", name: "ASHWATHY K N", subjects: ["Mathematics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_math_9", name: "VEERANNAGALA", subjects: ["Mathematics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_math_10", name: "PRAVEEN PATIL", subjects: ["Mathematics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_math_11", name: "SUPREETH JAIN", subjects: ["Mathematics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_math_12", name: "JAKAPURE", subjects: ["Mathematics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_math_13", name: "AMITH C S", subjects: ["Mathematics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_math_14", name: "RAMAKRISHNA", subjects: ["Mathematics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_math_15", name: "GANESH NAIK", subjects: ["Mathematics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_math_16", name: "PREETHI B", subjects: ["Mathematics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_math_17", name: "JISHA C P", subjects: ["Mathematics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_math_18", name: "NITHYASHREE", subjects: ["Mathematics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_math_19", name: "RAKESH H S", subjects: ["Mathematics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_math_20", name: "PRIYA S S", subjects: ["Mathematics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_math_21", name: "RAVULA RAMESH", subjects: ["Mathematics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_math_22", name: "ROOPESH POOJARI", subjects: ["Mathematics"], maxPeriodsPerDay: 4, isAbsent: false },

  // --- PHYSICS (31) ---
  { id: "fac_phys_1", name: "SATHYANARAYANA", subjects: ["Physics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_phys_2", name: "PRAKRATHI", subjects: ["Physics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_phys_3", name: "ROSHNI", subjects: ["Physics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_phys_4", name: "JIGISHU M K", subjects: ["Physics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_phys_5", name: "MANJULA A", subjects: ["Physics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_phys_6", name: "MANOHAR S R", subjects: ["Physics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_phys_7", name: "JOSTOM", subjects: ["Physics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_phys_8", name: "PRIYANKA", subjects: ["Physics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_phys_9", name: "DIVYA HEGDE", subjects: ["Physics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_phys_10", name: "BHAGYASHREE S", subjects: ["Physics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_phys_11", name: "MADHU BABU", subjects: ["Physics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_phys_12", name: "SUSHMITHA S", subjects: ["Physics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_phys_13", name: "ANASOOYA KUPPA", subjects: ["Physics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_phys_14", name: "VANDITHA", subjects: ["Physics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_phys_15", name: "SNEHA", subjects: ["Physics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_phys_16", name: "ASHWINI KOKADA", subjects: ["Physics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_phys_17", name: "NETHA SHETTY", subjects: ["Physics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_phys_18", name: "SHRIDAR G HULLUR", subjects: ["Physics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_phys_19", name: "JEWEL JOSEPH", subjects: ["Physics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_phys_20", name: "SRIDEVI", subjects: ["Physics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_phys_21", name: "ASHWINI", subjects: ["Physics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_phys_22", name: "NIREEKSHA M RAI", subjects: ["Physics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_phys_23", name: "SOHAN GOWDA", subjects: ["Physics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_phys_24", name: "Y GOWRI LAKSHMI", subjects: ["Physics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_phys_25", name: "SHREEKANTH K", subjects: ["Physics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_phys_26", name: "ROHITH", subjects: ["Physics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_phys_27", name: "SRINIVAS SHASTRI", subjects: ["Physics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_phys_28", name: "ASHIK K B", subjects: ["Physics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_phys_29", name: "SAJESH BABU", subjects: ["Physics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_phys_30", name: "AMALRAJ PANAYAN", subjects: ["Physics"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_phys_31", name: "SHILPA K", subjects: ["Physics"], maxPeriodsPerDay: 4, isAbsent: false },

  // --- SECOND LANGUAGE (19) ---
  { id: "fac_lang_1", name: "HEMALATHA", subjects: ["Second Language"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_lang_2", name: "SANJEEV K P", subjects: ["Second Language"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_lang_3", name: "LEKHAN H K", subjects: ["Second Language"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_lang_4", name: "JAYARAM", subjects: ["Second Language"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_lang_5", name: "DR NAVEEN", subjects: ["Second Language"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_lang_6", name: "MUNNER", subjects: ["Second Language"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_lang_7", name: "DISHA G C", subjects: ["Second Language"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_lang_8", name: "ROHITH M", subjects: ["Second Language"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_lang_9", name: "SAHANA BHANDARI", subjects: ["Second Language"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_lang_10", name: "HAREESHA K R", subjects: ["Second Language"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_lang_11", name: "VIDHYASHREE K R", subjects: ["Second Language"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_lang_12", name: "CHAITRA A S", subjects: ["Second Language"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_lang_13", name: "PRATHIK", subjects: ["Second Language"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_lang_14", name: "CHARAN KUMAR", subjects: ["Second Language"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_lang_15", name: "ARUN KUMAR KAN", subjects: ["Second Language"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_lang_16", name: "HARISHA DEVADIGA", subjects: ["Second Language"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_lang_17", name: "USHA B K", subjects: ["Second Language"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_lang_18", name: "ROHITH HV", subjects: ["Second Language"], maxPeriodsPerDay: 4, isAbsent: false },
  { id: "fac_lang_19", name: "THIPPE SWAMI", subjects: ["Second Language"], maxPeriodsPerDay: 4, isAbsent: false }
];