import type { Batch, Faculty, Allocation, Timetable } from '../types';
import { getSchedulerSettings } from './settings';

const parseTime = (timeStr: string) => {
  if (!timeStr) return 0;
  const [h, m] = timeStr.split(':').map(Number);
  return h * 60 + m;
};

const isOverlapping = (startA: string, endA: string, startB: string, endB: string) => {
  if (!startA || !endA || !startB || !endB) return false;
  return parseTime(startA) < parseTime(endB) && parseTime(endA) > parseTime(startB);
};

export const generateTimetableV2 = (
  batches: Batch[],
  faculties: Faculty[],
  existingDraft: Allocation[], 
  historicalData: Timetable[] 
): Allocation[] => {
  
  const settings = getSchedulerSettings();
  
  // 🚨 THE NUCLEAR FIX: Start by keeping ONLY the frozen cells. 
  // This instantly destroys any old assignments (including absent teachers).
  const allocations: Allocation[] = existingDraft.filter(a => a.frozen); 

  // Pre-calculate daily workloads based ONLY on frozen cells
  const dailyWorkload: Record<string, number> = {};
  allocations.forEach(a => {
    dailyWorkload[a.facultyId] = (dailyWorkload[a.facultyId] || 0) + 1;
  });

  // Main Scheduling Loop
  batches.forEach(batch => {
    batch.periods.forEach((periodTiming, pIndex) => {
      if (!periodTiming.startTime || !periodTiming.endTime) return;

      // Skip if a frozen cell already exists for this slot
      const hasFrozenCell = allocations.some(a => a.batchId === batch.id && a.periodIndex === pIndex);
      if (hasFrozenCell) return; 

      const targetSubject = batch.subjects.length > 0 ? batch.subjects[pIndex % batch.subjects.length].subject : 'Self Study';
      
      let candidateScores: { faculty: Faculty; score: number; reasons: string[] }[] = [];

      faculties.forEach(faculty => {
        // 🛑 STRICT ABSENT RULE
        if (faculty.isAbsent) return;

        if (!faculty.subjects.includes(targetSubject)) return;

        const currentLoad = dailyWorkload[faculty.id] || 0;
        const maxLimit = faculty.maxPeriodsPerDay || settings.maxDailyPeriods;
        if (currentLoad >= maxLimit) return;

        const hasTimeConflict = allocations.some(a => {
          if (a.facultyId !== faculty.id) return false;
          const otherBatch = batches.find(b => b.id === a.batchId);
          if (!otherBatch) return false;
          const otherTiming = otherBatch.periods[a.periodIndex];
          return isOverlapping(periodTiming.startTime, periodTiming.endTime, otherTiming.startTime, otherTiming.endTime);
        });

        if (hasTimeConflict) return;

        let score = 100;
        let reasons: string[] = ['Eligible for subject & time.'];

        score -= (currentLoad * 10);
        reasons.push(`Daily load penalty: -${currentLoad * 10}`);

        if (settings.enableConsecutivePeriodAvoidance) {
          const taughtLastPeriod = allocations.some(a => a.facultyId === faculty.id && a.batchId === batch.id && a.periodIndex === pIndex - 1);
          if (taughtLastPeriod) {
            score -= 50;
            reasons.push('Consecutive period penalty: -50');
          }
        }

        if (settings.enableGapOptimization) {
          const taughtBefore = allocations.some(a => a.facultyId === faculty.id && a.periodIndex === pIndex - 1);
          const teachesAfter = allocations.some(a => a.facultyId === faculty.id && a.periodIndex === pIndex + 1);
          if (taughtBefore || teachesAfter) {
             score += 15;
             reasons.push('Gap optimization bonus: +15');
          }
        }

        candidateScores.push({ faculty, score, reasons });
      });

      if (candidateScores.length > 0) {
        candidateScores.sort((a, b) => b.score - a.score); 
        const winner = candidateScores[0];

        allocations.push({
          batchId: batch.id,
          periodIndex: pIndex,
          facultyId: winner.faculty.id,
          subject: targetSubject,
          autoGenerated: true,
          manualEdited: false,
          frozen: false,
          explanation: winner.reasons
        });

        dailyWorkload[winner.faculty.id] = (dailyWorkload[winner.faculty.id] || 0) + 1;
      }
    });
  });

  return allocations;
};